### ISSUE TITLE
Cannot butt layers from separate artboards

### ISSUE THREAD

**Issue by pberrecloth** [pberrecloth/butter-sketch-plugin#16] opened 2017-09-08 15:43 UTC
If you select layers from separate artboards it will not butt them, displaying the message: "Please select multiple layers in a group". 

Similarly, if you multi-select an artboard and a layer from another artboard it does the same.

You should be able to butt items from different artboards, this included dartboards themselves. You should basically should be able to butt anything together regardless of which artboard it resides on.

**Comment by DWilliames** [comment] 2017-09-10 06:49
This is a great point — I think #17 encapsulates this better. Basically you should be able to butt any layers, whether they are in the same group, artboard or not.

**Comment by DWilliames** [comment] 2017-09-10 06:49
I might close this one at the moment as a duplicate of #17, and keep the discussion going in there.

**Closed as completed by DWilliames** 2017-09-10 06:49 UTC
Labels: duplicate
